version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: angelamcp
    environment:
      - DATABASE_URL=postgresql://angelamcp:angelamcp@postgres:5432/angelamcp
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    volumes:
      - ..:/app
      - ~/.claude:/home/angelamcp/.claude:ro
    stdin_open: true
    tty: true
    
  postgres:
    image: postgres:14-alpine
    container_name: angelamcp_postgres
    environment:
      - POSTGRES_USER=angelamcp
      - POSTGRES_PASSWORD=angelamcp
      - POSTGRES_DB=angelamcp
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
      
  redis:
    image: redis:7-alpine
    container_name: angelamcp_redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  redis_data:
