
services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: angelamcp
    env_file:
      - ../.env
    depends_on:
      - postgres
      - redis
    volumes:
      - ..:/app
      - ~/.claude:/home/angelamcp/.claude:ro
    stdin_open: true
    tty: true

  postgres:
    image: postgres:14-alpine
    container_name: angelamcp_postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: angelamcp_redis
    env_file:
      - ../.env
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  redis_data:
